name: AWS Three Tier Architecture setup using Terraform 

on:
  push:
    branches:
      - maser

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: "1.0.0"

      - name: Initialize Terraform
        run: terraform init

      - name: Format and validate Terraform
        run: terraform fmt -check -recursive && terraform validate

      - name: Plan Terraform
        run: terraform plan

      - name: Apply Terraform
        run: terraform apply -auto-approve
